# Generated by Django 3.2.11 on 2022-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
