# Generated by Django 3.2.11 on 2022-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220312_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='current_date',
            field=models.DateField(),
        ),
    ]
