# Generated by Django 3.2.11 on 2022-03-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogs_current_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='current_date',
            new_name='date',
        ),
    ]
